---
# Common tasks for all servers

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install common packages
  package:
    name:
      - git
      - curl
      - wget
      - vim
      - htop
      - unzip
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

- name: Set up timezone
  timezone:
    name: UTC

- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  when: ansible_os_family == "Debian"

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when: ansible_os_family == "Debian"

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Create app directory
  file:
    path: /opt/social-media-manager
    state: directory
    mode: '0755'

- name: Set up Python environment
  package:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
