---
# Main playbook for Social Media Manager application

- name: Configure common settings for all servers
  hosts: all
  become: yes
  roles:
    - common

- name: Deploy backend application
  hosts: app_servers
  become: yes
  roles:
    - backend

- name: Deploy frontend application
  hosts: app_servers
  become: yes
  roles:
    - frontend
